### ISSUE TITLE
FilterRequest may hide the real failure cause(exception) of a test

### ISSUE THREAD

**Issue by chang-chao** [junit-team/junit4#1277]
# Description
FilterRequest may hide the real failure cause(exception) of a test

# Steps To Reproduce
## 1. Write the following test code
<pre>
@RunWith(PowerMockRunner.class)
@PrepareForTest(value = { ClassUnderTest.class })
public class BarTest {

	@Test
	public void test() {
		System.out.println("hello world");
	}
}
</pre>

## 3.In eclipse,select the test method,and run as junit

# The expected result
The root cause,namely,javassist failure in stacktrace be shown.
In the case above,Exception javassist.bytecode.InterfaceMethodrefInfo cannot be cast to javassist.bytecode.MethodrefInfo should be seen.

# the current result
<pre>
BarTest.test
initializationError(org.junit.runner.manipulation.Filter)
java.lang.Exception: No tests found matching [{ExactMatcher:fDisplayName=test], {ExactMatcher:fDisplayName=test(BarTest)], {LeadingIdentifierMatcher:fClassName=BarTest,fLeadingIdentifier=test]] from org.junit.internal.requests.ClassRequest@72d1ad2e
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:77)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:68)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</pre>

# The reason and my suggested solution

Here is the getRunner code of the org.junit.internal.requests.FilterRequest class.

<pre>
    public Runner getRunner() {
        try {
            Runner runner = request .getRunner();
            fFilter.apply( runner);
            return runner ;
        } catch (NoTestsRemainException e ) {
            return new ErrorReportingRunner(Filter.class, new Exception(String
                    . format("No tests found matching %s from %s", fFilter
                            .describe(), request.toString())));
        }
    }
</pre>

It may be better  to be changed  into the following.
<pre>
    public Runner getRunner() {
        try {
            Runner runner = request .getRunner();

            if (runner instanceof ErrorReportingRunner) {
              // runner is already an ErrorReportingRunner
                return runner;
           }
            fFilter.apply( runner);
            return runner ;
        } catch (NoTestsRemainException e ) {
            return new ErrorReportingRunner(Filter.class, new Exception(String
                    . format("No tests found matching %s from %s", fFilter
                            .describe(), request.toString())));
        }
    }
</pre>

**Comment by kcooney** [comment]
Based on the discussion on #1279 I think this should be fixed on the Eclipse side. @chang-chao could you file.a big against Eclipse for this?

**Comment by chang-chao** [comment]
A bug is filed against to Eclipse.
https://bugs.eclipse.org/bugs/show_bug.cgi?id=491752

**Comment by kcooney** [comment]
@chang-chao thanks. I suggest updating the Eclipse bug to have the same steps to reproduce that you had here.

It's possible that they need to keep that `throw` there but need to check if the runner is `ErrorReportingRunner`

**Comment by chang-chao** [comment]
@kcooney Thanks for the adivce,the bug description in eclipse bugzilla is updated.

**Comment by Stephan972** [comment]
Hi guys,

We are in 2020 now...  this terrible bug still happen even with JUnit 5 !

On the 13th of January 2020, the Eclipse team asked for some more details here : https://bugs.eclipse.org/bugs/show_bug.cgi?id=491752#c3 (comment 3).

Can you please answer them ?

**Comment by dr0i** [comment]
@Stephan972 had the same issue, wouldn't get away, just after I rebuild from commandline: `./gradlew build`.

**Comment by kcooney** [comment]
We closed this because we believe the bug is in Eclipse, not JUnit (see discussion on #1279).

If you can reproduce this bug, comment on the Eclipse bug with the details they are asking for.

**Comment by dr0i** [comment]
Than it's not just a bug in Eclipse but also in Codium - I am not saying that's not an IDE issue - on the contrary. Just noting.

**Comment by kcooney** [comment]
@dr0i please file a new bug with a minimal, complete, and verifiable example that demonstrates the problem (see https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by dr0i** [comment]
@kcooney funny that you point to SO - 'cause [that got me here](https://stackoverflow.com/questions/47710837/junit-testing-got-initializationerror-with-java-lang-exception-no-tests-found-m/68863902#68863902) in the first place :) (answered there, see "codium as IDE").
So, just in case of possible misunderstanding, I am with you: seems not to be a junit4 issue, you are good, it is some kind of IDE problem which can be solved by manually rebuilding the project.
If you meant to file a bug at codium: I might (and would reference it here then), but don't see the need now that I know how to come along this issue.
